/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import Lean
import ProofWidgets.Component.Panel.Basic
import ProofWidgets.Component.HtmlDisplay
import VersoBlueprint.Data
import VersoBlueprint.Environment
import VersoBlueprint.Graph
import VersoBlueprint.PreviewRender

open Lean Elab Command
open ProofWidgets

section BlueprintWidget

structure GraphParams where
  /-- Graph title shown in the panel summary. -/
  title : String
  /-- Informal label requested by the user. -/
  label : String
  /-- HTML generated by the Verso informal renderer. -/
  statementHtml : Json
  /-- DOT source to render. -/
  dot : String
  /-- TeX macro prelude shared with KaTeX rendering. -/
  texPrelude : String := ""
  deriving Server.RpcEncodable

@[widget_module]
def blueprintWidget : Component GraphParams where
  javascript := "
    import d3 from 'https://cdn.jsdelivr.net/npm/d3@7.9.0/+esm'
    import { graphviz } from 'https://cdn.jsdelivr.net/npm/d3-graphviz@5.6.0/+esm'
    import katex from 'https://cdn.jsdelivr.net/npm/katex@0.16.27/+esm'
    import * as React from 'react';

    export default function ({ title, label, statementHtml, dot, texPrelude }) {
        const graphRef = React.useRef(null);

        function loadStyle(url) {
          const attr = 'data-bp-widget-katex';
          if (document.head.querySelector(`link[${attr}='1']`)) return;
          const link = document.createElement('link');
          link.rel = 'stylesheet';
          link.type = 'text/css';
          link.href = url;
          link.setAttribute(attr, '1');
          document.head.appendChild(link);
        }

        React.useEffect(() => {
           loadStyle('https://cdn.jsdelivr.net/npm/katex@0.16.28/dist/katex.min.css');
           if (graphRef.current && dot) {
             graphviz(graphRef.current)
               .fit(true)
               .renderDot(dot);
           }
        }, [dot]);

        const prelude = typeof texPrelude === 'string' ? texPrelude.trim() : '';
        const debug = (() => {
          if (window.__versoTexPreludeDebug) return true;
          try {
            return window.localStorage && window.localStorage.getItem('verso.texPrelude.debug') === '1';
          } catch (_err) {
            return false;
          }
        })();
        const log = (...args) => {
          if (debug && window.console && typeof window.console.log === 'function') {
            window.console.log('[bp widget texPrelude]', ...args);
          }
        };
        log('widget mounted', { preludeLen: prelude.length });

        const rootStyle = { display: 'grid', gap: '0.6rem', fontSize: '0.9rem', lineHeight: 1.45 };
        const statementStyle = {
          marginTop: '0.2rem',
          paddingLeft: '0.35rem',
          borderLeft: '2px solid #e2e8f0',
          maxHeight: '15rem',
          overflowY: 'auto'
        };
        const legendStyle = {
          display: 'grid',
          gap: '0.45rem',
          fontSize: '0.75rem'
        };
        const legendGroupStyle = {
          display: 'grid',
          gap: '0.22rem'
        };
        const legendGroupTitleStyle = {
          fontSize: '0.68rem',
          fontWeight: 700,
          letterSpacing: '0.03em',
          textTransform: 'uppercase',
          color: '#334155'
        };
        const itemStyle = {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '0.35rem'
        };
        const swatch = ({ fill, border = '#6b7280', radius = '0.12rem', width = '0.72rem', height = '0.72rem', double = false }) => React.createElement('span', {
          style: {
            width,
            height,
            border: `${double ? 3 : 1}px solid ${border}`,
            borderRadius: radius,
            background: fill
          }
        });
        const gradient = (top, bottom) => `linear-gradient(180deg, ${top}, ${bottom})`;
        const legendGroup = (key, title, items) => React.createElement('div', { key, style: legendGroupStyle }, [
          React.createElement('div', { key: `${key}-title`, style: legendGroupTitleStyle }, title),
          ...items
        ]);
        const extractText = node => {
          if (typeof node === 'string') return node;
          if (Array.isArray(node)) return node.map(extractText).join('');
          if (!node || typeof node !== 'object') return '';
          if (typeof node.raw === 'string') return node.raw;
          if (typeof node.tag === 'string') return extractText(node.content);
          return '';
        };
        const renderHtml = (node, key = 'root') => {
          if (typeof node === 'string') return node;
          if (Array.isArray(node)) {
            return React.createElement(
              React.Fragment,
              { key },
              node.map((x, i) => renderHtml(x, `${key}-${i}`))
            );
          }
          if (!node || typeof node !== 'object') {
            return React.createElement('span', { key }, String(node));
          }
          if (typeof node.raw === 'string') {
            return React.createElement('span', { key, dangerouslySetInnerHTML: { __html: node.raw } });
          }
          if (typeof node.tag === 'string') {
            const props = { key };
            const attrs = Array.isArray(node.attrs) ? node.attrs : [];
            const classAttr = attrs.find(a => a && a.name === 'class');
            const classes = typeof classAttr?.value === 'string' ? classAttr.value : '';
            if (node.tag === 'code' && classes.includes('math')) {
              const tex = extractText(node.content);
              const displayMode = classes.includes('display');
              let rendered = tex;
              const renderToStringWrapped =
                !!(katex && typeof katex.renderToString === 'function' && katex.renderToString.__versoTexPreludeWrapped);
              const renderInput = (prelude.length > 0 && !renderToStringWrapped) ? `${prelude}\n${tex}` : tex;
              log('math render input', {
                texLen: tex.length,
                renderInputLen: renderInput.length,
                displayMode,
                renderToStringWrapped,
                prependedHere: prelude.length > 0 && !renderToStringWrapped
              });
              try {
                rendered = katex.renderToString(renderInput, { throwOnError: false, displayMode });
              } catch (err) {
                log('renderToString error', err);
              }
              return React.createElement(displayMode ? 'div' : 'span', {
                key,
                dangerouslySetInnerHTML: { __html: rendered }
              });
            }
            for (const attr of attrs) {
              if (!attr || typeof attr.name !== 'string') continue;
              const name = attr.name === 'class' ? 'className' : attr.name;
              props[name] = typeof attr.value === 'string' ? attr.value : '';
            }
            return React.createElement(node.tag, props, renderHtml(node.content, `${key}-content`));
          }
          return React.createElement('code', { key }, JSON.stringify(node));
        };

        return React.createElement('div', { style: rootStyle }, [
          React.createElement('div', {
            key: 'informal',
            style: { padding: '0.2rem 0', fontSize: '0.86rem' }
          }, [
            React.createElement('div', { key: 'title', style: { fontWeight: 600, marginBottom: '0.35rem' } }, [
              'Informal statement preview for ',
              React.createElement('code', { key: 'v' }, label || '(none)')
            ]),
            React.createElement('div', {
              key: 'rv',
              style: statementStyle
            }, renderHtml(statementHtml, 'stmtHtml'))
          ]),
          React.createElement('details', { key: 'graphPanel' }, [
            React.createElement('summary', {
              key: 'summary',
              style: { cursor: 'pointer', fontWeight: 600 }
            }, title || 'Blueprint graph'),
            React.createElement('div', { key: 'body', style: { marginTop: '0.35rem', display: 'grid', gap: '0.5rem' } }, [
              React.createElement('div', { key: 'legend', style: legendStyle }, [
                legendGroup('shape', 'Shapes', [
                  React.createElement('span', { key: 'shape-def', style: itemStyle }, [swatch({ fill: '#ffffff', border: '#64748b' }), 'Definition (box)']),
                  React.createElement('span', { key: 'shape-thm', style: itemStyle }, [swatch({ fill: '#ffffff', border: '#64748b', radius: '999px' }), 'Theorem/lemma/corollary (ellipse)'])
                ]),
                legendGroup('statement', 'Statement border', [
                  React.createElement('span', { key: 'st-blocked', style: itemStyle }, [swatch({ fill: '#ffffff', border: '#f59e0b' }), 'Blocked']),
                  React.createElement('span', { key: 'st-ready', style: itemStyle }, [swatch({ fill: '#ffffff', border: '#2563eb' }), 'Ready to formalize']),
                  React.createElement('span', { key: 'st-formalized', style: itemStyle }, [swatch({ fill: '#ffffff', border: '#16a34a' }), 'Formalized']),
                  React.createElement('span', { key: 'st-mathlib', style: itemStyle }, [swatch({ fill: '#ffffff', border: '#14532d' }), 'In Mathlib'])
                ]),
                legendGroup('proof', 'Background status', [
                  React.createElement('span', { key: 'pf-none', style: itemStyle }, [swatch({ fill: '#f8fafc', border: '#64748b' }), 'Not ready']),
                  React.createElement('span', { key: 'pf-ready', style: itemStyle }, [swatch({ fill: '#dbeafe', border: '#64748b' }), 'Ready to formalize']),
                  React.createElement('span', { key: 'pf-formalized', style: itemStyle }, [swatch({ fill: '#dcfce7', border: '#64748b' }), 'Formalized']),
                  React.createElement('span', { key: 'pf-anc', style: itemStyle }, [swatch({ fill: '#166534', border: '#14532d' }), 'Formalized + ancestors'])
                ]),
                legendGroup('warning', 'Warning overlays', [
                  React.createElement('span', { key: 'warn-unknown', style: itemStyle }, [swatch({ fill: '#fee2e2', border: '#b91c1c' }), 'Unknown reference']),
                  React.createElement('span', { key: 'warn-lean-only', style: itemStyle }, [swatch({ fill: gradient('#ffffff', '#ede9fe'), border: '#16a34a' }), 'Lean code, informal statement missing']),
                  React.createElement('span', { key: 'warn-local-sorry', style: itemStyle }, [swatch({ fill: gradient('#dbeafe', '#fef3c7'), border: '#2563eb' }), 'Local sorries']),
                  React.createElement('span', { key: 'warn-deps', style: itemStyle }, [swatch({ fill: '#dcfce7', border: '#16a34a', double: true }), 'Formalized node with incomplete ancestors'])
                ]),
                legendGroup('edges', 'Edges', [
                  React.createElement('span', { key: 'edges-stmt', style: itemStyle }, 'Solid: theorem/lemma deps'),
                  React.createElement('span', { key: 'edges-def', style: itemStyle }, 'Dashed: definition-source deps'),
                  React.createElement('span', { key: 'edges-proof', style: itemStyle }, 'Dotted: proof-only deps')
                ])
              ]),
              React.createElement('div', {
                key: 'graph',
                ref: graphRef,
                style: {
                  minHeight: '12rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '0.35rem',
                  padding: '0.25rem',
                  background: '#ffffff'
                }
              })
            ])
          ])
        ]);
    }"

end BlueprintWidget

abbrev GraphNode := Informal.Graph.GraphNode Unit
abbrev Graph := Informal.Graph.Graph Unit

def graphDotHeader : String := r##"strict digraph "" {
  rankdir=LR;
  bgcolor="white";
  splines=true;
  nodesep=0.35;
  ranksep=0.45;
  node [shape=box, style="rounded,filled", fontname="Helvetica", fontsize=9, margin="0.05,0.03", color="#6b7280", penwidth=1.4];
  edge [color="#6b7280", arrowhead=vee, arrowsize=0.5, penwidth=0.9];
  graph [fontname="Helvetica"];"##

def Graph.toDot (g : Graph) : String :=
  Informal.Graph.Graph.toDot g graphDotHeader

open Informal Data Environment
structure BuildResult where
  dot : String
  statementElab : Array Syntax
  texPrelude : String

def buildFor [Monad m] [MonadEnv m] [MonadError m] (label : Name) : m BuildResult := do
  let state := informalExt.getState (← getEnv)
  let some root := state.data.get? label
    | do
      let available :=
        state.data.toArray
          |>.map (·.1.toString)
          |>.take 12
      throwError m!"No Label Found for '{label}'. Known labels (first {available.size}): {String.intercalate ", " available.toList}"
  let graph : Graph := Informal.Graph.build state #[label]
  let dot := graph.toDot
  let texPrelude ← Environment.getTexPrelude
  pure { dot, statementElab := (root.statement.map (·.elabStx)).getD #[], texPrelude }

open Server in
def updatePanel (title label : String) (statementHtml : Json) (dot texPrelude : String) stx :=
  Widget.savePanelWidgetInfo
    (blueprintWidget.javascriptHash)
    (rpcEncode ({ title, label, statementHtml, dot, texPrelude } : GraphParams )) stx

def activateForLabelDoc (label : Name) (stx : Syntax) : Verso.Doc.Elab.DocElabM Unit := do
  if stx.getPos?.isNone then
    return ()
  let out ← buildFor label
  let statementHtml := toJson (← Informal.renderStatementElabHtml out.statementElab)
  (monadLift (updatePanel s!"BluePrint widget: {label}" label.toString statementHtml out.dot out.texPrelude stx) : Verso.Doc.Elab.DocElabM Unit)

show_panel_widgets [local blueprintWidget]

/-- Graph command -/
syntax (name := showGraph) "#show_graph" str : command

@[command_elab showGraph]
unsafe def elabGraph : CommandElab := fun
  | stx@`(#show_graph $label:str) => do
    let target := Name.mkSimple label.getString
    let out ← liftCoreM <| buildFor target
    let statementHtml := toJson (← Lean.Elab.Command.liftTermElabM <| Informal.renderStatementElabHtml out.statementElab)
    liftCoreM <| updatePanel s!"BluePrint widget: {target}" label.getString statementHtml out.dot out.texPrelude stx
  | _ => throwUnsupportedSyntax

-- #show_graph exampleGraph
