/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import Lean
import ProofWidgets.Component.Panel.Basic
import ProofWidgets.Component.HtmlDisplay
import VersoBlueprint.Data
import VersoBlueprint.Environment
import VersoBlueprint.PreviewRender

open Lean Elab Command
open ProofWidgets

section BlueprintWidget

structure GraphParams where
  /-- Graph title shown in the panel summary. -/
  title : String
  /-- Informal label requested by the user. -/
  label : String
  /-- HTML generated by the Verso informal renderer. -/
  statementHtml : Json
  /-- DOT source to render. -/
  dot : String
  /-- TeX macro prelude shared with KaTeX rendering. -/
  texPrelude : String := ""
  deriving Server.RpcEncodable

@[widget_module]
def blueprintWidget : Component GraphParams where
  javascript := "
    import d3 from 'https://cdn.jsdelivr.net/npm/d3@7.9.0/+esm'
    import { graphviz } from 'https://cdn.jsdelivr.net/npm/d3-graphviz@5.6.0/+esm'
    import katex from 'https://cdn.jsdelivr.net/npm/katex@0.16.27/+esm'
    import * as React from 'react';

    export default function ({ title, label, statementHtml, dot, texPrelude }) {
        const graphRef = React.useRef(null);

        function loadStyle(url) {
          const attr = 'data-bp-widget-katex';
          if (document.head.querySelector(`link[${attr}='1']`)) return;
          const link = document.createElement('link');
          link.rel = 'stylesheet';
          link.type = 'text/css';
          link.href = url;
          link.setAttribute(attr, '1');
          document.head.appendChild(link);
        }

        React.useEffect(() => {
           loadStyle('https://cdn.jsdelivr.net/npm/katex@0.16.28/dist/katex.min.css');
           if (graphRef.current && dot) {
             graphviz(graphRef.current)
               .fit(true)
               .renderDot(dot);
           }
        }, [dot]);

        const prelude = typeof texPrelude === 'string' ? texPrelude.trim() : '';

        const rootStyle = { display: 'grid', gap: '0.6rem', fontSize: '0.9rem', lineHeight: 1.45 };
        const statementStyle = {
          marginTop: '0.2rem',
          paddingLeft: '0.35rem',
          borderLeft: '2px solid #e2e8f0',
          maxHeight: '15rem',
          overflowY: 'auto'
        };
        const legendStyle = {
          display: 'flex',
          flexWrap: 'wrap',
          gap: '0.45rem 0.8rem',
          fontSize: '0.75rem'
        };
        const itemStyle = {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '0.35rem'
        };
        const swatch = color => React.createElement('span', {
          style: {
            width: '0.7rem',
            height: '0.7rem',
            border: '1px solid #6b7280',
            borderRadius: '0.12rem',
            background: color
          }
        });
        const extractText = node => {
          if (typeof node === 'string') return node;
          if (Array.isArray(node)) return node.map(extractText).join('');
          if (!node || typeof node !== 'object') return '';
          if (typeof node.raw === 'string') return node.raw;
          if (typeof node.tag === 'string') return extractText(node.content);
          return '';
        };
        const renderHtml = (node, key = 'root') => {
          if (typeof node === 'string') return node;
          if (Array.isArray(node)) {
            return React.createElement(
              React.Fragment,
              { key },
              node.map((x, i) => renderHtml(x, `${key}-${i}`))
            );
          }
          if (!node || typeof node !== 'object') {
            return React.createElement('span', { key }, String(node));
          }
          if (typeof node.raw === 'string') {
            return React.createElement('span', { key, dangerouslySetInnerHTML: { __html: node.raw } });
          }
          if (typeof node.tag === 'string') {
            const props = { key };
            const attrs = Array.isArray(node.attrs) ? node.attrs : [];
            const classAttr = attrs.find(a => a && a.name === 'class');
            const classes = typeof classAttr?.value === 'string' ? classAttr.value : '';
            if (node.tag === 'code' && classes.includes('math')) {
              const tex = extractText(node.content);
              const displayMode = classes.includes('display');
              let rendered = tex;
              const renderInput = prelude.length > 0 ? `${prelude}\n${tex}` : tex;
              try {
                rendered = katex.renderToString(renderInput, { throwOnError: false, displayMode });
              } catch (_err) {}
              return React.createElement(displayMode ? 'div' : 'span', {
                key,
                dangerouslySetInnerHTML: { __html: rendered }
              });
            }
            for (const attr of attrs) {
              if (!attr || typeof attr.name !== 'string') continue;
              const name = attr.name === 'class' ? 'className' : attr.name;
              props[name] = typeof attr.value === 'string' ? attr.value : '';
            }
            return React.createElement(node.tag, props, renderHtml(node.content, `${key}-content`));
          }
          return React.createElement('code', { key }, JSON.stringify(node));
        };

        return React.createElement('div', { style: rootStyle }, [
          React.createElement('div', {
            key: 'informal',
            style: { padding: '0.2rem 0', fontSize: '0.86rem' }
          }, [
            React.createElement('div', { key: 'title', style: { fontWeight: 600, marginBottom: '0.35rem' } }, [
              'Informal statement preview for ',
              React.createElement('code', { key: 'v' }, label || '(none)')
            ]),
            React.createElement('div', {
              key: 'rv',
              style: statementStyle
            }, renderHtml(statementHtml, 'stmtHtml'))
          ]),
          React.createElement('details', { key: 'graphPanel' }, [
            React.createElement('summary', {
              key: 'summary',
              style: { cursor: 'pointer', fontWeight: 600 }
            }, title || 'Blueprint graph'),
            React.createElement('div', { key: 'body', style: { marginTop: '0.35rem', display: 'grid', gap: '0.5rem' } }, [
              React.createElement('div', { key: 'legend', style: legendStyle }, [
                React.createElement('span', { key: 'def', style: itemStyle }, [swatch('#bfdbfe'), 'Definition']),
                React.createElement('span', { key: 'leanOnly', style: itemStyle }, [swatch('#e9d5ff'), 'Lean-only entry (informal missing)']),
                React.createElement('span', { key: 'ok', style: itemStyle }, [swatch('#d4f4dd'), 'Lean + proof']),
                React.createElement('span', { key: 'sorry', style: itemStyle }, [swatch('#fff3bf'), 'Proof pending']),
                React.createElement('span', { key: 'informal', style: itemStyle }, [swatch('#f3f4f6'), 'Informal/text-only']),
                React.createElement('span', { key: 'unresolved', style: itemStyle }, [swatch('#fee2e2'), 'Unresolved dependency']),
                React.createElement('span', { key: 'edges', style: itemStyle }, 'Edges: solid = statement, dashed = proof')
              ]),
              React.createElement('div', {
                key: 'graph',
                ref: graphRef,
                style: {
                  minHeight: '12rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '0.35rem',
                  padding: '0.25rem',
                  background: '#ffffff'
                }
              })
            ])
          ])
        ]);
    }"

end BlueprintWidget

structure GraphNode where
  label : Name
  deps : List Name
  proofDeps : List Name := []
  fillcolor : String
deriving Inhabited

def Graph := List GraphNode

def definitionNodeColor : String := "#bfdbfe"
def leanOnlyDefNodeColor : String := "#e9d5ff"
def leanOkNodeColor : String := "#d4f4dd"
def sorryNodeColor : String := "#fff3bf"
def informalNodeColor : String := "#f3f4f6"
def unresolvedDepNodeColor : String := "#fee2e2"

def nodeHasSorries (node : Informal.Data.Node) : Bool :=
  match node.code.map (·.info) with
  | none => false
  | some info => info.definedDefs.any (·.hasSorry) || info.definedTheorems.any (·.hasSorry)

def nodeColor (node : Informal.Data.Node) : String :=
  if node.code.isSome && node.statement.isNone then
    leanOnlyDefNodeColor
  else if node.kind == Informal.Data.NodeKind.definition then
    definitionNodeColor
  else if node.code.isSome then
    if nodeHasSorries node then sorryNodeColor
    else if node.proof.isSome then leanOkNodeColor
    else sorryNodeColor
  else
    informalNodeColor

def Graph.toDot (g : Graph) : String :=
  let known : NameSet := g.foldl (init := {}) fun acc node => acc.insert node.label
  let nodes := g.map fun node =>
    s!"  \"{node.label}\" [label=\"{node.label}\", fillcolor=\"{node.fillcolor}\"];"
  let edges := g.flatMap fun node =>
    node.deps.filterMap fun dep =>
      if known.contains dep then
        some s!"  \"{node.label}\" -> \"{dep}\";"
      else
        none
  let proofEdges := g.flatMap fun node =>
    node.proofDeps.filterMap fun dep =>
      if known.contains dep then
        some s!"  \"{node.label}\" -> \"{dep}\" [style=dashed, penwidth=1.2];"
      else
        none
  String.intercalate "\n" ([header] ++ nodes ++ edges ++ proofEdges ++ ["}"])
where
  header := r##"strict digraph "" {
  rankdir=LR;
  bgcolor="white";
  splines=true;
  nodesep=0.35;
  ranksep=0.45;
  node [shape=box, style="rounded,filled", fontname="Helvetica", fontsize=9, margin="0.05,0.03", color="#6b7280", penwidth=1.4];
  edge [color="#6b7280", arrowhead=vee, arrowsize=0.5, penwidth=0.9];
  graph [fontname="Helvetica"];"##

def mkNode (state : Informal.Environment.State) (label : Name) : GraphNode :=
  match state.data.get? label with
  | some node =>
    {
      label
      deps := ((node.statement.map (·.deps)).getD #[]).toList
      proofDeps := ((node.proof.map (·.deps)).getD #[]).toList
      fillcolor := nodeColor node
    }
  | none =>
    {
      label
      deps := []
      proofDeps := []
      fillcolor := unresolvedDepNodeColor
    }

open Informal Data Environment
structure BuildResult where
  dot : String
  statementElab : Array Syntax
  texPrelude : String

def buildFor [Monad m] [MonadEnv m] [MonadError m] (label : Name) : m BuildResult := do
  let state := informalExt.getState (← getEnv)
  let some root := state.data.get? label
    | do
      let available :=
        state.data.toArray
          |>.map (·.1.toString)
          |>.take 12
      throwError m!"No Label Found for '{label}'. Known labels (first {available.size}): {String.intercalate ", " available.toList}"
  let stmtDeps : List Name := ((root.statement.map (·.deps)).getD #[]).toList.map (fun d => (d : Name))
  let prfDeps : List Name := ((root.proof.map (·.deps)).getD #[]).toList.map (fun d => (d : Name))
  let labels : List Name := (label :: stmtDeps ++ prfDeps).eraseDups
  let graph : Graph := labels.map (mkNode state)
  let dot := graph.toDot
  pure { dot, statementElab := (root.statement.map (·.elabStx)).getD #[], texPrelude := state.texPrelude }

open Server in
def updatePanel (title label : String) (statementHtml : Json) (dot texPrelude : String) stx :=
  Widget.savePanelWidgetInfo
    (blueprintWidget.javascriptHash)
    (rpcEncode ({ title, label, statementHtml, dot, texPrelude } : GraphParams )) stx

def activateForLabelDoc (label : Name) (stx : Syntax) : Verso.Doc.Elab.DocElabM Unit := do
  if stx.getPos?.isNone then
    return ()
  let out ← buildFor label
  let statementHtml := toJson (← Informal.renderStatementElabHtml out.statementElab)
  (monadLift (updatePanel s!"BluePrint widget: {label}" label.toString statementHtml out.dot out.texPrelude stx) : Verso.Doc.Elab.DocElabM Unit)

show_panel_widgets [local blueprintWidget]

/-- Graph command -/
syntax (name := showGraph) "#show_graph" str : command

@[command_elab showGraph]
unsafe def elabGraph : CommandElab := fun
  | stx@`(#show_graph $label:str) => do
    let target := Name.mkSimple label.getString
    let out ← liftCoreM <| buildFor target
    let statementHtml := toJson (← Lean.Elab.Command.liftTermElabM <| Informal.renderStatementElabHtml out.statementElab)
    liftCoreM <| updatePanel s!"BluePrint widget: {target}" label.getString statementHtml out.dot out.texPrelude stx
  | _ => throwUnsupportedSyntax

-- #show_graph exampleGraph
